### ISSUE TITLE
Main menu items icon size

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#10]
Hello, SychO9,
After installing Potato theme, some of items in main forum menu are displayed with larger icon size (30x30 pixels). Default icon size is 16x16 pixels. I mean items added by additional installed mods - SMF Gallery, Team page, Contact, Tinyportal etc.
I will attach a screenshot from my forum.
![2020-09-25](https://user-images.githubusercontent.com/68983397/94227469-38bb3880-ff03-11ea-8652-02a267276246.png)

**Comment by SychO9** [comment]
Interesting, I forgot mods could add icon images, the 30x30 pixel was added for the avatar, looks like it has to be more precisely targeted at the avatar to not affect icon images.

Thank you for the report.

**Comment by SychO9** [comment]
Fixed in 13e4eb04e46a04d6006a50b13f389de78b4cef7a
