### ISSUE TITLE
Strange scrollbar appears on some posts

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#13]
I have noticed that some posts have unnecessary vertical scrollbar.
The issue appears only if the post contains hyperlink **at the end**. If the hyperlink is on another place (at beginning of the post or somewhere else), the vertical scrollbar does not appear.
I will attach a screenshot from my test forum.
![2020-09-26](https://user-images.githubusercontent.com/68983397/94331805-2fe86680-ffd8-11ea-8f59-023169c6479a.png)

**Comment by SychO9** [comment]
Does it also happen with the default theme ?

**Comment by Hatshepsut71** [comment]
No, only with Potato theme.
That's the look of the same topic with default theme:
![2020-09-26 (1)](https://user-images.githubusercontent.com/68983397/94338546-d5f99800-fffb-11ea-8b12-23298e25d4b5.png)
