### ISSUE TITLE
Quick Edit doesn't work

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#14]
In my forums with Potato theme installed, Quick Edit doesn't work.
When I click on appropriate icon, the Edit frame appears, but after editing text and then clicking Save button, changes are not saved.
You can see that issue directly on my test forum: https://bg-nacionalisti.org/test/index.php

Username: tester
Password: for123test

**Comment by SychO9** [comment]
Yup an issue indeed, fixed in https://github.com/SychO9/smf-potato-theme/commit/4e2a42ee10b25809a7312c7055df46568bec888e

Thank you for the report.
