### ISSUE TITLE
Statbars in user profiles are too short

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#16]
Statbars in user profiles, dispaying user activity by hours, are too short and with same size. Related number of posts in each statbar is not visible.
I will attach a screenshot for my user profile in my forum
![2020-09-27](https://user-images.githubusercontent.com/68983397/94356286-3a1c6a80-0095-11eb-8720-c89b9584460f.png)

**Comment by SychO9** [comment]
well this is no good
