### ISSUE TITLE
"More emoticons" frame issues

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#18]
Isssues with "More emoticons" frame window in Potato theme are two:

1. When using Quick Reply
In that case, the "More emoticons" frame does not appear. It's hidden, and I need to maximize Quick Reply window to see the frame.
![2020-09-27 (2)](https://user-images.githubusercontent.com/68983397/94362091-a01ee700-00c1-11eb-87c7-de2a75f8ed69.png)

2. When using Full Reply
In that case, the "More emoticons" frame appears, but only part of it is visible. Lower part of frame with Close button is not accessible
![2020-09-27 (3)](https://user-images.githubusercontent.com/68983397/94362148-f0964480-00c1-11eb-984c-7db39f986d63.png)

**Comment by SychO9** [comment]
this is a weird one, the smiley popup should not be affected at all by the theme's CSS since it has its own CSS code in the sceditor plugin's whole CSS file. I suppose there was something included in the index.css of the theme for this (which shouldn't have been).
