### ISSUE TITLE
Text in Calendar hard to read in Dark mode

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#19]
When I switch Potato theme to Dark mode, the text in Calendar is hard to read - font color is similar to background color.
I will attach a screenshot from my forum.
![2020-09-28 (1)](https://user-images.githubusercontent.com/68983397/94467027-0b081500-01cb-11eb-849b-f9c024b1aa82.png)

**Comment by SychO9** [comment]
Thank you for the report.

This has already been fixed in the commits https://github.com/SychO9/smf-potato-theme/commit/21d53b8e11940738055cf4b2eb67e8f83e4f9c37 & https://github.com/SychO9/smf-potato-theme/commit/69e6aeffba652cdfb6f86f9394e648f56a2e406c
