### ISSUE TITLE
Text in statblocks is hard to read in Light mode

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#20]
In SMF 2.1, statblocks is used in Forum stats page, Memberlist, and in the polls.
In Light mode, text in statblocks is hard to read (white font on grey background).
I will attach a screnshot from my forum.
![2020-09-30](https://user-images.githubusercontent.com/68983397/94644833-fcb51880-02f2-11eb-98ec-9803c5b99fcc.png)

I would suggest, if it's possible, to use separate statbars, like in SMF 2.0. With this variant, changing the secondary theme color will never affect the text in stats page. This variant is also used by additional mods - SMF Gallery, Download System, and Tinyportal in their stats pages.
I will attach a screenshot from my forum, showing Download System stats page.
![2020-09-30 (1)](https://user-images.githubusercontent.com/68983397/94644983-5ae1fb80-02f3-11eb-9073-d15ac9cb14b4.png)

**Comment by SychO9** [comment]
I would rather avoid editing the statbar structures for a different style, mods tend to add their own stats there so it could get messy.

I think a text shadow would solve the issue, making the white text stand out.

Either an outline style like this:
![Screenshot from 2020-09-30 10-30-47](https://user-images.githubusercontent.com/20267363/94669187-d39f8280-0308-11eb-944b-2c7f9e13f620.png)

or a simple drop shadow:
![Screenshot from 2020-09-30 10-36-48](https://user-images.githubusercontent.com/20267363/94669282-edd96080-0308-11eb-9acb-6a3735e14729.png)

**Comment by SychO9** [comment]
I thin I'll go with this after all:
![Screenshot from 2020-09-30 15-43-21](https://user-images.githubusercontent.com/20267363/94700843-da8fba80-0333-11eb-88a0-00bc3f178bea.png)

**Comment by SychO9** [comment]
Fixed in https://github.com/SychO9/smf-potato-theme/commit/48774d6f4b65e8597fb4b78571b938aa820e05ed
