### ISSUE TITLE
"Board permissions" table structure is destroyed

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#22]
"Board permissions" table structure in Potato theme is destroyed.
I will attach a screenshot from my forum.
![2020-10-01 (1)](https://user-images.githubusercontent.com/68983397/94852511-a8b14d80-0432-11eb-8696-77de823e2591.png)

For comparision, that's the look of the same page with default theme:
![2020-10-01 (2)](https://user-images.githubusercontent.com/68983397/94852615-d5656500-0432-11eb-84e5-1c958ec3141c.png)

**Comment by SychO9** [comment]
woah ! that looks hideous ! Thank you for the report.

**Comment by SychO9** [comment]
![smf lan_index php_action=admin;area=permissions;sa=board;a08ce22b0=d4c199e11ccf3a43a6664aa19fc41e7a;theme=2](https://user-images.githubusercontent.com/20267363/94868776-be774080-043b-11eb-9932-1bd0daf131d8.png)
