### ISSUE TITLE
Some item names in Main menu are hard to read in Light mode

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#23]
In Light mode, when in Main forum menu there are too many items, some of them are placed in the light area, and it's hard to read their names.
In my case, only one item is placed in the light area, but if the user's display is with lower resolution, it's possible that the main menu will be wrapped in two rows.
I will attach a screenshot from my forum.
![2020-10-02](https://user-images.githubusercontent.com/68983397/94889669-afb57b80-0485-11eb-9257-2dc5b7432e48.png)

I think adding of an outline, drop shadow or local backround for item labels will resolve this.

**Comment by SychO9** [comment]
While a text effect would make it clearer, It wouldn't look so nice with the simple header design :thinking: 

Instead I think stretching out the waves svg when the menu has more than 8 items would be better, just enough for the last menu items to be visible.
