### ISSUE TITLE
Personal Messages Index not properly styled

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#27]
There are duplicates values in Personal Messages Index table.
In column 'Subject' are displayed values from other columns - 'Date' and 'From'. Also, these values are displayed in their related columns.
I will attach a screenshot from my forum.
![2020-10-05 (1)](https://user-images.githubusercontent.com/68983397/95079686-a6474000-071f-11eb-838f-fc29e72fbdda.png)

And a screenshot from same page with default theme.
![2020-10-05 (2)](https://user-images.githubusercontent.com/68983397/95079763-bc550080-071f-11eb-96c2-f174435d3b52.png)

**Comment by SychO9** [comment]
Damn, I forgot to style up the personal messages template.
