### ISSUE TITLE
Secondary Color: Doesn't appear to do anything.

### ISSUE THREAD

**Issue by lurkalot** [SychO9/smf-potato-theme#37]
Secondary Color: Doesn't appear to do anything. Running potato_0.1.0.tar downloaded from here, GH.  And on SMF 2.1 RC3

Primary Color:  seems to change fine.

**Comment by SychO9** [comment]
Hey thanks for the report!

Yea the secondary color is actually only used in maybe 4 or 5 elements, like the alerts counter in the header if you take a look at the screenshots. It's not a noticeable color at first, but you'll see it used eventually :P
