### ISSUE TITLE
Mark user votes in polls with bold text

### ISSUE THREAD

**Issue by Hatshepsut71** [SychO9/smf-potato-theme#38]
With SMF default theme, user votes in polls are marked with bold text, so they can be remembered by user and eventually changed in the future (if such option is enabled).
![2020-10-10](https://user-images.githubusercontent.com/68983397/95654379-3d3d3f00-0b08-11eb-834b-109e935b3482.png)

With Potato theme, user votes are displayed with normal text as votes of another users and they are not remarkable...
![2020-10-10 (1)](https://user-images.githubusercontent.com/68983397/95654382-47f7d400-0b08-11eb-8e05-2a114c55bb92.png)

**Comment by SychO9** [comment]
nice catch!
