### ISSUE TITLE
Wrong view of attached images

### ISSUE THREAD

**Issue by dragomano** [SychO9/smf-potato-theme#42]
Attachments do not fit in the area assigned to them and are arranged in a row.

Example => https://dragomano.ru/forum/index.php?topic=3.new;topicseen;theme=2

The default theme has no this problem => https://dragomano.ru/forum/index.php?topic=3.new;topicseen;theme=1

**Comment by SychO9** [comment]
huh Interesting, I forgot to add a `flex-wrap` there, thank you for the report !

**Comment by dragomano** [comment]
For .attachments?

**Comment by SychO9** [comment]
yup
