### ISSUE TITLE
SMF 2.0.18 /Sources/Load.php(2272) : eval()'d code on line 76

### ISSUE THREAD

**Issue by Cerbere1980** [SychO9/smf-potato-theme#45]
Hello,
I wanted to install the theme on a new SMF 2.0.18 installation.

I get this error message when I activate it.

Fatal error: require_once(): Failed opening required '/XXXX/Sources/src/vendor.php' (include_path='.:/opt/php7.3/lib/php') in /XXXX/Sources/Load.php(2272) : eval()'d code on line 76

An idea of the fix?

**Comment by SychO9** [comment]
This theme is not compatible with 2.0, it is a 2.1 theme.

**Comment by Cerbere1980** [comment]
All right, thank you.
