### ISSUE TITLE
Impossible to support smf 2.0.18?

### ISSUE THREAD

**Issue by linuxhw** [SychO9/smf-potato-theme#48]

**Comment by SychO9** [comment]
Sorry, impossible, that would mean rewriting the whole thing.

**Comment by linuxhw** [comment]
BTW how some themes support both 2.0 and 2.1? Like https://custom.simplemachines.org/index.php?theme=2930

**Comment by SychO9** [comment]
> BTW how some themes support both 2.0 and 2.1? Like https://custom.simplemachines.org/index.php?theme=2930

By providing a different package for each version, see the packages list in that page.
